//Notifications for every patients
const dailyActivityReminder = {
    id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    largeIcon: "ic_launcher", // (optional) default: "ic_launcher" //use app's icon
    smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
    ticker: "วันนี้อย่าลืมทำกิจกรรมนะ",
    ongoing: false,
    tag: 'daily', // (optional) add tag to message
    title: "วันนี้อย่าลืมทำกิจกรรมล่ะ ", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
    message: "อย่างน้อยวันละ 2 ครั้งนะ", // (required)
    playSound: true, // (optional) default: true
    soundName: 'default',
    actions: '["Yes", "No"]',
    repeatType: 'day',
    date: new Date(Date.now() + (5 * 1000)), //Wait for 5 seconds before notify for the first time
}



const dailyImportanceReminder = {
    id: '1',
    largeIcon: "ic_launcher",
    smallIcon: "ic_notification",
    ticker: "วันนี้อย่าลืมทำกิจกรรมนะ",
    ongoing: false,
    tag: 'daily',
    title: "ถ้าพร้อมแล้วก็เริ่มทำกิจกรรมเลย!",
    message: "ยิ่งทำบ่อยก็ยิ่งได้กลับบ้านเร็ว",
    playSound: true,
    soundName: 'default',
    repeatType: 'daily',
    date: new Date(Date.now() + (10 * 1000)),
}

const reachLevel4 = {
    id: '0',
    largeIcon: "ic_launcher",
    smallIcon: "ic_notification",
    ticker: "มาได้ครึ่งทางแล้วนะ",
    ongoing: false,
    tag: 'motivate',
    message: "มาได้ครึ่งทางแล้วนะ",
    playSound: true,
    soundName: 'default',
}

const reachLevel6 = {
    id: '1',
    largeIcon: "ic_launcher",
    smallIcon: "ic_notification",
    ticker: "ทำกิจกรรมถึงขั้นที่ 6 แล้ว อีกนิดเดียว!",
    ongoing: false,
    tag: 'motivate',
    message: "ทำกิจกรรมถึงขั้นที่ 6 แล้ว อีกนิดเดียว!",
    playSound: true,
    soundName: 'default',
}

const reachLevel7 = {
    id: '2',
    largeIcon: "ic_launcher",
    smallIcon: "ic_notification",
    ticker: "ยินดีด้วย! ทำได้ครบทุกขั้นแล้ว",
    ongoing: false,
    tag: 'motivate',
    message: "ยินดีด้วย! ทำได้ครบทุกขั้นแล้ว",
    playSound: true,
    soundName: 'default',
}

//Notifications for patients who smoke or have lung disease
const dailyReminderForBreathing = {
    id: '0',
    largeIcon: "ic_launcher",
    smallIcon: "ic_notification",
    ticker: "2 ชั่วโมงแล้ว ฝึกหายใจด้วยนะ",
    ongoing: false,
    tag: 'condition',
    title: "2 ชั่วโมงแล้ว ฝึกหายใจด้วยนะ",
    message: "2 ชั่วโมงแล้ว ฝึกหายใจด้วยนะ",
    playSound: true,
    soundName: 'default',
    actions: '["Yes", "No"]',
    repeatType: 'time',
    repeatTime: 7200000, //Notify every 2 hours
    date: new Date(Date.now() + (1 * 1000)),
}

//Notifications for patients who classified as high risk
const reminderForHighRiskPatient = {
    id: '1',
    largeIcon: "ic_launcher",
    smallIcon: "ic_notification",
    ticker: "มีความเสี่ยงสูง โปรดระวังขณะเปลี่ยนท่า",
    ongoing: false,
    tag: 'condition',
    title: "มีความเสี่ยงสูง โปรดระวังขณะเปลี่ยนท่า",
    message: "มีความเสี่ยงสูง โปรดระวังขณะเปลี่ยนท่า",
    playSound: true,
    soundName: 'default',
    repeatType: 'day',
    date: new Date(Date.now() + (10 * 1000)),
}

//Notifications for patients who classified as high risk
const reminderForSapheneousVeinPatient = {
    id: '2',
    largeIcon: "ic_launcher",
    smallIcon: "ic_notification",
    ticker: "ผู้ป่วยเลาะเส้นเลือดที่ขา โปรดระวังขาบวม",
    ongoing: false,
    tag: 'condition',
    title: "ผู้ป่วยเลาะเส้นเลือดที่ขา โปรดระวังขาบวม",
    message: "ผู้ป่วยเลาะเส้นเลือดที่ขา โปรดระวังขาบวม",
    playSound: true,
    soundName: 'default',
    repeatType: 'day',
    date: new Date(Date.now() + (15 * 1000)),
}

const reminderForNotDoingActivityYet = {
    id: '3',
    largeIcon: "ic_launcher",
    smallIcon: "ic_notification",
    ticker: "ยังไม่ได้ทำกิจกรรมเลยนะ อย่าลืมทำล่ะ",
    ongoing: false,
    tag: 'condition',
    title: "ยังไม่ได้ทำกิจกรรมเลยนะ อย่าลืมทำล่ะ",
    message: "ยังไม่ได้ทำกิจกรรมเลยนะ อย่าลืมทำล่ะ",
    playSound: true,
    soundName: 'default',
}

//Notifications for patients who classified as high risk
const reminderForDailyLife = {
    id: '4',
    largeIcon: "ic_launcher",
    smallIcon: "ic_notification",
    ticker: "ถ้าทำได้ ก็ทำกิจวัตรประจำวันด้วยตัวเองนะ",
    ongoing: false,
    tag: 'condition',
    title: "ถ้าทำได้ ก็ทำกิจวัตรประจำวันด้วยตัวเองนะ",
    message: "ถ้าทำได้ ก็ทำกิจวัตรประจำวันด้วยตัวเองนะ",
    playSound: true,
    soundName: 'default',
    repeatType: 'day',
    date: new Date(Date.now() + (10 * 1000)),
}

export { dailyActivityReminder, dailyReminderForBreathing, dailyImportanceReminder, reachLevel4, reachLevel6, reachLevel7, reminderForHighRiskPatient, reminderForSapheneousVeinPatient, reminderForNotDoingActivityYet, reminderForDailyLife }
